version: "3.9" # version of docker container syntax

services:           # docker compose file typically consist of one or more service that neede for your application
  app:              # name of our service
    build:          # build and context . -> the docker file insider our current directory 
      context: .
      args:
        - DEV=true
    ports:          # this maps 8000 on the local machine and container
      - "8000:8000"
    volumes:        # maping directories from our system to docker container
      - ./app:/app
    command: >      # this is command to run the service
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data: